title: Dmitry Shpika
subtitle: Hacking HTML since 2005

environment: production
production_url: https://scriptin.github.io

permalink: /:year-:month-:day/:title.html

exclude:
  - "update_css.sh"
  - "README.md"
  - "devbox.json"
  - "devbox.lock"
  - ".devbox"
  - ".editorconfig"
  - ".idea"
