title: Dmitry Shpika
subtitle: on programming languages, tools and practices

environment: production
production_url: http://scriptin.github.io

permalink: /:year-:month-:day/:title.html

safe: true
lsi: false
markdown: kramdown
highlighter: rouge

exclude: ["update_css.sh", "README.md", "Dockerfile"]
