title: Dmitry Shpika
subtitle: I'm a software developer

environment: production
production_url: https://scriptin.github.io

permalink: /:year-:month-:day/:title.html

exclude: ["update_css.sh", "README.md", "Dockerfile", ".editorconfig"]
