title: "little smart things"
subtitle: "because there's already enough of big stupid things"
pygments: true
permalink: /:year-:month-:day/:title.html
url: http://scriptin.github.io
baseurl: /
exclude: ["Vagrantfile", "chef", "start_dev_server.sh"]
