title: scriptin's thoughts
subtitle: on programming languages, tools and practices
author_fullname: Dmitry Shpika
author_nickname: scriptin
production_url: http://scriptin.github.io

safe: true
lsi: false
pygments: true
permalink: /:year-:month-:day/:title.html
url: http://scriptin.github.io
baseurl: /
exclude: ["Vagrantfile", "chef", "start_dev_server.sh"]
