title: Dmitry Shpika
subtitle: // Hacking HTML since 2005

environment: production
production_url: https://scriptin.github.io
permalink: /:year-:month-:day/:title.html

exclude:
  - "README.md"
  - "devbox.json"
  - "devbox.lock"
  - ".devbox"
  - "node_modules"
  - "package.json"
  - "package-lock.json"
  - ".editorconfig"
  - ".idea"
