title: Dmitry Shpika

environment: production
production_url: https://scriptin.github.io
permalink: /:year-:month-:day/:title.html

exclude:
  - "README.md"
  - "devbox.json"
  - "devbox.lock"
  - ".devbox"
  - "less"
  - "node_modules"
  - "package.json"
  - "package-lock.json"
  - ".editorconfig"
  - ".idea"
