title: scriptin's thoughts
subtitle: on programming languages, tools and practices

author_fullname: Dmitry Shpika
author_nickname: scriptin

environment: production
url: http://scriptin.github.io
production_url: http://scriptin.github.io
baseurl: /

permalink: /:year-:month-:day/:title.html

safe: true
lsi: false
highlighter: pygments

exclude: ["Vagrantfile", "chef", "start_dev_server.sh"]
