title: Dmitry Shpika
subtitle: on programming languages, tools and practices

environment: development

permalink: /:year-:month-:day/:title.html

safe: true
lsi: false
markdown: kramdown
highlighter: pygments

exclude: ["Vagrantfile", "chef", "start_dev_server.sh"]
